### ISSUE TITLE
Number format error

### ISSUE THREAD

**Issue by MartinSzollos2016** [h4kuna/exchange-nette#3]
Version 0.1.2 requires exchange "h4kuna/exchange": "^5.0" which require "h4kuna/number-format": "^2.0".
Composer install number format 2.0.2 which exist on packagist (https://packagist.org/packages/h4kuna/number-format#v2.0.2) but not on github. 
So you get number-format version 3 installed and got error:
Class 'h4kuna\Number\Utils\Crate' not found.

**Comment by h4kuna** [comment]
Thank you version is deleted, i think 15 minutes and all will be alright.

**Comment by h4kuna** [comment]
If you are upgrading on nette 3 lets try use dev-master

**Comment by MartinSzollos2016** [comment]
I would like to try nette 3, but exchange has still in composer "nette/http": "^2.4"

**Comment by h4kuna** [comment]
Ok, i fix it

**Comment by h4kuna** [comment]
Could you try install `"h4kuna/exchange-nette": "dev-master"`?

It work for me with option `"minimum-stability": "dev",`

**Comment by MartinSzollos2016** [comment]
I already did. Now it works.

**Comment by MartinSzollos2016** [comment]
I will test it in my app.
Thanks for quick update.

**Comment by h4kuna** [comment]
You welcome
